# sonarqube/sonar-project.properties
sonar.projectKey=secure-share
sonar.projectName=Secure Share
sonar.projectVersion=1.0
sonar.sources=client/src,server/src
sonar.tests=client/src/__tests__,server/src/__tests__
sonar.language=typescript
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript specific settings
sonar.organization=thaison1939

sonar.typescript.node=18
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.testExecutionReportPaths=client/coverage/test-report.xml

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts

# Coverage exclusions
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/dist/**

# Security hotspots
sonar.security.hotspots.includePaths=client/src,server/src