# k8s/infrastructure/argocd-repo-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/thaison1939/secure-share.git
  password: your-github-token
  username: yourusername